server:
  port: 8102
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zwang:123456@localhost:8005/eureka/ #同时注册到两个注册中心
