server:
  port: 8102
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://first:8002/eureka/,http://second:8003/eureka/ #同时注册到两个注册中心