server:
  port: 8005
spring:
  application:
    name: eureka-security-server
  security: #配置SpringSecurity登录用户名和密码
    user:
      name: zwang
      password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      defaultZone: http://zwang:123456@localhost:8004/eureka/