server:
  port: 8301
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zwang:123456@localhost:8001/eureka/
service-url:
  gym-management: http://gym-management
